/* Generated by Reason Relay Compiler 0.1.0, PLEASE EDIT WITH CARE */

type query = {
  id: option(string),
  name: option(string),
  married: option(bool),
  age: option(int),
  closeRate: option(float),
}